### ISSUE TITLE
Incorrect docs PREG_REPLACE

### ISSUE THREAD

**Issue by jasny** [mysqludf/lib_mysqludf_preg#2]
I think there is a problem in the documentation of:

http://www.mysqludf.org/lib_mysqludf_preg/index.php#PREG_REPLACE_SECTION

if I do:

```
SELECT PREG_REPLACE('/(.*?)(fox)/' , 'dog' , 'the quick brown fox' );
```

the result is not the same as it says in the webpage.

**Comment by richwaters** [comment]
I think there is an issue with a "$1" being removed by a shell or something while you were testing. The docs on the website (or at least the index.html file) specify the replacement at '$1dog'

So, the line:

PREG_REPLACE('/(.*?)(fox)/' , '$1dog' , 'the quick brown fox' )

does indeed return:

+-----------------------------------------------------------------+
| PREG_REPLACE('/(.*?)(fox)/' , '$1dog' , 'the quick brown fox' ) |
+-----------------------------------------------------------------+
| the quick brown dog                                             |
+-----------------------------------------------------------------+

as stated in the documentation
