### ISSUE TITLE
errot aclocal 

### ISSUE THREAD

**Issue by adnankhairy** [mysqludf/lib_mysqludf_preg#8]
i recived this error when i try to exc "make insatall" & "make installdb" & "make uninstall"

"/usr/local/src/lib_mysqludf_preg-testing/config/missing: line 81: aclocal-1.13: command not found
WARNING: 'aclocal-1.13' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
make: **\* [aclocal.m4] Error 127"

how can i fix this?

**Comment by adnankhairy** [comment]
i got it worked now, sorry

but i have a problem with my RegEx code can you please help me!

my column is contained some text & some html tags i need to delete all img tags from this coulmn what can i do to achieve this ?

this is my ReGex

/</?(?i:img)(.|\n)*?>/g

but i don't know how to make this any help please

**Comment by stefancrain** [comment]
A few notes @adnankhairy, Other people might also be seeing this issue so providing your solution would be super helpful (I'm having the same issue for example).

Also, if you are having trouble with a regex that doesn't relate to the original issue please open a new issue to track the progress.

**Comment by adnankhairy** [comment]
@stefancrain  i have solved it but iam very very sorry i don't remember how 

but i remember that this issue is from the server itself not from the plugin the make cmd not installed fully in your server so you need to reinstall it

try to google this 
"WARNING: 'aclocal-1.13' is missing on your system. make install" 

hope this help you

**Comment by stefancrain** [comment]
After some research it turns out my aclocal was a different version then the config required which was causing the failure.

`$ aclocal --version`
returned:

```
aclocal (GNU automake) 1.11.3
Copyright (C) 2011 Free Software Foundation, Inc.
.......
```

in the config file changing line 2378 from `am__api_version='1.13'` to `am__api_version='1.11'` was all I needed.

**Comment by adnankhairy** [comment]
glad to hear that

**Comment by trel** [comment]
Instead of changing the `./configure` file directly, you can have the autoconf toolchain rebuild the things it needs with the correct versions based on what's on your system at the time.

```
$ autoreconf --force --install
```

Then run the standard install and test...

```
./configure
make
sudo make install
sudo make installdb
sudo make test
```

When complete, you should be able to see the six new functions:

```
$ mysql -uroot mysql -e "select * from func"
+------------------------+-----+----------------------+----------+
| name                   | ret | dl                   | type     |
+------------------------+-----+----------------------+----------+
| preg_position          |   2 | lib_mysqludf_preg.so | function |
| preg_rlike             |   2 | lib_mysqludf_preg.so | function |
| preg_replace           |   0 | lib_mysqludf_preg.so | function |
| lib_mysqludf_preg_info |   0 | lib_mysqludf_preg.so | function |
| preg_capture           |   0 | lib_mysqludf_preg.so | function |
| preg_check             |   2 | lib_mysqludf_preg.so | function |
+------------------------+-----+----------------------+----------+
```

I confirmed this works on stock installs of:
- Ubuntu 10.x
- Ubuntu 12.x
- CentOS 6.x
- SuSE 11.x
- SuSE 12.x

CentOS 5.x returns an undefined symbol when trying to load the .so:

```
$ sudo make installdb
/usr/bin/mysql  <./uninstalldb.sql
if test -f .libs/lib_mysqludf_preg.dll; then  \
                /usr/bin/mysql  <./installdb_win.sql; \
        else \
                /usr/bin/mysql  <./installdb.sql;\
        fi
ERROR 1126 (HY000) at line 3: Can't open shared library 'lib_mysqludf_preg.so' (errno: 22 /usr/local/lib/lib_mysqludf_preg.so: undefined symbol: my_thread_stack_size)
make: *** [installdb] Error 1
```
